In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [3]:
a.dtype

dtype('int32')

In [4]:
a.size

4

In [5]:
type('a')

str

In [6]:
type(a)

numpy.ndarray

In [7]:
a.ndim

1

In [8]:
a.shape

(4,)

In [10]:
b=np.array([[1,2,3],[3,4,4]])

In [11]:
b.size

6

In [12]:
type(b)

numpy.ndarray

In [13]:
b.ndim

2

In [14]:
b.shape

(2, 3)

In [16]:
b.itemsize

4

In [17]:
c = np.array([[1,2,3],[4,5,6]])

In [18]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
c.size

6

In [20]:
c.itemsize

4

In [22]:
d = np.array([[1,2,3],(4,5,6)])

In [23]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
e = np.array(((1,2,3),(4,5,6),(7,8,9)))

In [26]:
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
g = ([['a','b'],['c','d']])

In [30]:
g

[['a', 'b'], ['c', 'd']]

In [33]:
type(g)

list

In [42]:
f = np.array([[1,2,3],[4,5,6]],dtype='uint')

In [43]:
f

array([[1, 2, 3],
       [4, 5, 6]], dtype=uint32)

In [44]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
np.ones((4,1))

array([[1.],
       [1.],
       [1.],
       [1.]])

In [46]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(5,9)

array([5, 6, 7, 8])

In [53]:
np.arange(0,12,3)

array([0, 3, 6, 9])

In [54]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [65]:
np.linspace(0,12,3).reshape(3,1)

array([[ 0.],
       [ 6.],
       [12.]])

In [66]:
np.random.random(3)

array([0.54600663, 0.62034939, 0.07840774])

In [67]:
np.random.random((3,3))

array([[0.22795833, 0.83969536, 0.41702157],
       [0.8958197 , 0.53503555, 0.63232668],
       [0.54546638, 0.72130176, 0.12307617]])

In [69]:
np.random(0,10)

TypeError: 'module' object is not callable

In [70]:
a = np.arange(0,4)

In [71]:
b= np.arange(4,8)

In [72]:
b

array([4, 5, 6, 7])

In [73]:
a

array([0, 1, 2, 3])

In [74]:
c = a+b

In [75]:
c

array([ 4,  6,  8, 10])

In [76]:
a *np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [77]:
a*np.sqrt(b)

array([0.        , 2.23606798, 4.89897949, 7.93725393])

In [78]:
np.sqrt(b)

array([2.        , 2.23606798, 2.44948974, 2.64575131])

In [79]:
A = np.arange(0,9).reshape(3,3)

In [80]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [81]:
B = np.ones((3,3))

In [82]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [83]:
C = A*B

In [84]:
C

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [85]:
D = np.dot(A,B)

In [86]:
D

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [87]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [88]:
a= np.arange(4)

In [89]:
a +=2

In [90]:
a

array([2, 3, 4, 5])

In [91]:
a *=2

In [92]:
a

array([ 4,  6,  8, 10])

In [94]:
a = np.arange(1,5)

In [95]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [96]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [97]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [98]:
a = np.array([3.3,4.5,6.7,7.9])

In [99]:
a.sum()

22.4

In [100]:
a.std()

1.8027756377319948

In [101]:
a.mean()

5.6

In [102]:
a.max()

7.9

In [103]:
a =np.arange(10,16)

In [104]:
a

array([10, 11, 12, 13, 14, 15])

In [105]:
a[4]

14

In [106]:
a[-1]

15

In [109]:
a[[2,4]]

array([12, 14])

In [110]:
A = np.arange(10,19).reshape(3,3)

In [125]:
A[[2,2],[0,1]]

array([16, 17])

In [126]:
A = np.arange(10,16)

In [127]:
A [1:5]

array([11, 12, 13, 14])

In [128]:
A

array([10, 11, 12, 13, 14, 15])

In [129]:
A[1:5:2]

array([11, 13])

In [130]:
A[::2]

array([10, 12, 14])

In [131]:
C = np.arange(10,19).reshape(3,3)

In [132]:
C[0,:]

array([10, 11, 12])

In [133]:
C

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [135]:
C[:,0]

array([10, 13, 16])

In [136]:
C[0:2,0:2]

array([[10, 11],
       [13, 14]])

In [142]:
C[[1,2],1:2]

array([[14],
       [17]])

In [143]:
for row in C:
    print(row)

[10 11 12]
[13 14 15]
[16 17 18]


In [145]:
for item in A.flat:
    print(item)

10
11
12
13
14
15


In [148]:
np.apply_along_axis(np.mean,axis=1,arr=C)

array([11., 14., 17.])

In [150]:
def foo(x):
    return x/2

In [153]:
np.apply_along_axis(foo,axis=1,arr=C)

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])

In [154]:
A = np.random.random((4,4))

In [155]:
A<0.5

array([[False, False, False,  True],
       [False, False, False,  True],
       [False, False,  True, False],
       [False,  True,  True, False]])

In [157]:
A[A<0.5]

array([0.00679781, 0.13774664, 0.09059744, 0.31323932, 0.19706773])

In [158]:
a = np.random.random(12)

In [159]:
a

array([0.73855626, 0.95783624, 0.76943978, 0.85098339, 0.5997398 ,
       0.75381419, 0.02738516, 0.66904893, 0.1174241 , 0.25757353,
       0.72549287, 0.00697664])

In [160]:
a.reshape(4,3)

array([[0.73855626, 0.95783624, 0.76943978],
       [0.85098339, 0.5997398 , 0.75381419],
       [0.02738516, 0.66904893, 0.1174241 ],
       [0.25757353, 0.72549287, 0.00697664]])

In [161]:
a

array([0.73855626, 0.95783624, 0.76943978, 0.85098339, 0.5997398 ,
       0.75381419, 0.02738516, 0.66904893, 0.1174241 , 0.25757353,
       0.72549287, 0.00697664])

In [162]:
a.shape=(3,4)

In [163]:
a

array([[0.73855626, 0.95783624, 0.76943978, 0.85098339],
       [0.5997398 , 0.75381419, 0.02738516, 0.66904893],
       [0.1174241 , 0.25757353, 0.72549287, 0.00697664]])

In [164]:
a.ravel()

array([0.73855626, 0.95783624, 0.76943978, 0.85098339, 0.5997398 ,
       0.75381419, 0.02738516, 0.66904893, 0.1174241 , 0.25757353,
       0.72549287, 0.00697664])

In [165]:
a.shape=(2,6)

In [166]:
a

array([[0.73855626, 0.95783624, 0.76943978, 0.85098339, 0.5997398 ,
        0.75381419],
       [0.02738516, 0.66904893, 0.1174241 , 0.25757353, 0.72549287,
        0.00697664]])

In [167]:
a.ravel()

array([0.73855626, 0.95783624, 0.76943978, 0.85098339, 0.5997398 ,
       0.75381419, 0.02738516, 0.66904893, 0.1174241 , 0.25757353,
       0.72549287, 0.00697664])

In [168]:
a.reshape(6,2)

array([[0.73855626, 0.95783624],
       [0.76943978, 0.85098339],
       [0.5997398 , 0.75381419],
       [0.02738516, 0.66904893],
       [0.1174241 , 0.25757353],
       [0.72549287, 0.00697664]])

In [169]:
A = np.ones((3,3))
b = np.zeros((3,3))

In [170]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [171]:
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [172]:
A.dot(b)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [173]:
A+b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [174]:
np.vstack((A,b))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [175]:
np.hstack((b,A))

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [178]:
a =np.arange(0,3)

In [179]:
a

array([0, 1, 2])

In [180]:
b=np.arange(3,6)

In [181]:
b

array([3, 4, 5])

In [183]:
c=np.arange(6,9)

In [184]:
c

array([6, 7, 8])

In [185]:
np.column_stack((a,b,c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [186]:
np.row_stack((a,b,c))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [188]:
np.vstack((a,b,c))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [201]:
A = np.arange(0,16).reshape(4,4)

In [202]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [203]:
[B,C] = np.hsplit(A,2)

In [204]:
B

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [205]:
C

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [206]:
A=np.arange(0,16).reshape(4,4)

In [208]:
B =np.arange(0,4)

In [209]:
A*B

array([[ 0,  1,  4,  9],
       [ 0,  5, 12, 21],
       [ 0,  9, 20, 33],
       [ 0, 13, 28, 45]])

In [215]:
m=np.arange(6).reshape(3,1,2)

In [216]:
m

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [217]:
n =np.arange(6).reshape(3,1,2)

In [218]:
n

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [219]:
m+n

array([[[ 0,  2]],

       [[ 4,  6]],

       [[ 8, 10]]])

In [224]:
np.arange[[4,4]]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [232]:
data = np.arange(4,4).reshape(2,2)

ValueError: cannot reshape array of size 0 into shape (2,2)

In [233]:
data = np.random.random((4,4))

In [234]:
data

array([[0.71997236, 0.21779458, 0.57439637, 0.0202158 ],
       [0.14534334, 0.60649941, 0.60205782, 0.36325093],
       [0.75499479, 0.54173212, 0.55826849, 0.00492503],
       [0.6398427 , 0.90225563, 0.79224449, 0.67188377]])

In [235]:
np.save('saved_data',data)

In [236]:
loaded_data = np.load('saved_data.npy')

In [237]:
loaded_data

array([[0.71997236, 0.21779458, 0.57439637, 0.0202158 ],
       [0.14534334, 0.60649941, 0.60205782, 0.36325093],
       [0.75499479, 0.54173212, 0.55826849, 0.00492503],
       [0.6398427 , 0.90225563, 0.79224449, 0.67188377]])